# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_config_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='VelocityChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity_name', models.TextField(blank=True, null=True)),
                ('velocity_time', models.TextField(blank=True, null=True)),
                ('velocity_times', models.TextField(blank=True, null=True)),
                ('velocity_amount', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VelocityLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity_id', models.TextField(blank=True, null=True)),
                ('mobile_number', models.TextField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
